name: nimbus_service
services:
  nimbus_service:
    working_dir: /code/src
    command: uvicorn --log-level debug app:app --host $NIMBUS__APP_HOST --port $NIMBUS__APP_PORT --reload
    build: ..
    environment:
      - LOGGING_LEVEL
      - UPLOAD_DIR_URL=/code/src/DATA
    ports:
      - "${NIMBUS__APP_PORT}:${NIMBUS__APP_PORT}"
    volumes:
      - ../src:/code/src
